### ISSUE TITLE
Splitview

### ISSUE THREAD

**Issue by martinRenou** [kolibril13/jupyter-splitview#1]
Don't hesitate to ask me any questions here.

Let me suggest to start by defining your widget model. I would suggest using a widget constructed like this:

```python
class SplitView(DOMWidget):
    _model_name = Unicode('SplitViewModel').tag(sync=True)
    _view_name = Unicode('SplitViewView').tag(sync=True)

    left = Instance(Widget).tag(sync=True, **widget_serialization)
    right = Instance(Widget).tag(sync=True, **widget_serialization)
```

You can look at widgets libraries like https://github.com/QuantStack/ipytree or https://github.com/martinRenou/ipycanvas to get some ideas.

**Comment by martinRenou** [comment]
In case you use gitter: https://gitter.im/martinRenou

**Comment by kolibril13** [comment]
Thanks, after two years I've now used another approach:
Instead of [widget-cookiecutter](https://github.com/jupyter-widgets/widget-cookiecutter) I've used a `@magics_class` in [sw_cellmagic.py](https://github.com/kolibril13/jupyter-splitview/blob/master/jupyter_splitview/sw_cellmagic.py) and took the JavaScript implementation of the split view widget from  https://github.com/NUKnightLab/juxtapose.
